# ---------------------------------------------  启动端口 ------------------------------------------------------- #
server:
  port: 8080

spring:
# ---------------------------------------------  数据库配置(默认使用mysql：5.5+) -----------------------------------#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_manager?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

# ---------------------------------------------  配置 JPA ------------------------------------------------------- #
  jpa:
    hibernate:
# ---------------------------------------------  更新策略 ------------------------------------------------------- #
      ddl-auto: update
# ---------------------------------------------  打印SQL ------------------------------------------------------- #
    show-sql: true
# ---------------------------------------------  自动生成表结构 ------------------------------------------------- #
    generate-ddl: true
# --------------------------------------------- 配置mybatis ---------------------------------------------------- #
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
